/**
 * Placeholder PDF Builder for eCTD 4.0 Submissions
 * Generates simple placeholder PDFs with document metadata
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate a placeholder PDF file
 * @param {string} filePath - Output file path
 * @param {object} options - PDF options
 * @param {string} options.title - Document title
 * @param {string} options.type - Document type
 * @param {string} options.module - CTD module (m1-m5)
 * @param {string} options.appNumber - Application number
 * @param {number} options.sequenceNumber - Sequence number
 * @returns {Promise<void>}
 */
async function generatePlaceholderPDF(filePath, options) {
  return new Promise((resolve, reject) => {
    try {
      // Ensure directory exists
      const dir = path.dirname(filePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      
      // Create PDF document
      const doc = new PDFDocument({
        size: 'LETTER',
        margins: { top: 72, bottom: 72, left: 72, right: 72 },
        info: {
          Title: options.title,
          Author: 'eCTD Generator',
          Subject: `${options.type} - ${options.module}`,
          Keywords: 'eCTD, FDA, placeholder'
        }
      });
      
      // Pipe to file
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);
      
      // Header
      doc.fontSize(24)
         .font('Helvetica-Bold')
         .text('PLACEHOLDER DOCUMENT', { align: 'center' });
      
      doc.moveDown(2);
      
      // Document info box
      doc.fontSize(12)
         .font('Helvetica');
      
      // Draw border
      const boxTop = doc.y;
      doc.rect(72, boxTop, 468, 180).stroke();
      
      doc.moveDown(0.5);
      
      // Document details
      const details = [
        { label: 'Document Title:', value: options.title },
        { label: 'Document Type:', value: options.type },
        { label: 'CTD Module:', value: options.module.toUpperCase() },
        { label: 'Application Number:', value: options.appNumber || 'N/A' },
        { label: 'Sequence Number:', value: options.sequenceNumber?.toString() || 'N/A' },
        { label: 'Generated:', value: new Date().toISOString() }
      ];
      
      details.forEach(({ label, value }) => {
        doc.font('Helvetica-Bold')
           .text(label, 90, doc.y, { continued: true, width: 150 })
           .font('Helvetica')
           .text(` ${value}`, { width: 300 });
        doc.moveDown(0.3);
      });
      
      doc.moveDown(3);
      
      // Notice
      doc.fontSize(10)
         .font('Helvetica-Oblique')
         .fillColor('#666666')
         .text(
           'This is a placeholder document generated for eCTD 4.0 submission testing purposes. ' +
           'Replace this file with the actual document content before regulatory submission.',
           { align: 'center' }
         );
      
      // Footer
      doc.fontSize(8)
         .fillColor('#999999')
         .text(
           'Generated by eCTD 4.0 Submission Generator',
           72, 720,
           { align: 'center' }
         );
      
      // Finalize PDF
      doc.end();
      
      stream.on('finish', () => resolve());
      stream.on('error', (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Generate multiple placeholder PDFs for a submission
 * @param {Array} documents - Array of document configurations
 * @param {object} paths - Paths from dirBuilder
 * @param {string} appNumber - Application number
 * @param {number} sequenceNumber - Sequence number
 * @param {function} getDocPath - Function to get document path
 * @returns {Promise<Array<{doc: object, filePath: string}>>} - Array of generated documents
 */
async function generateSubmissionPDFs(documents, paths, appNumber, sequenceNumber, getDocPath) {
  const results = [];
  
  for (const doc of documents) {
    // Skip if document has an existing file path
    if (doc.filePath && fs.existsSync(doc.filePath)) {
      results.push({ doc, filePath: doc.filePath, generated: false });
      continue;
    }
    
    const filePath = getDocPath(paths, doc, appNumber, sequenceNumber);
    
    await generatePlaceholderPDF(filePath, {
      title: doc.title,
      type: doc.type,
      module: doc.module,
      appNumber,
      sequenceNumber
    });
    
    results.push({ doc, filePath, generated: true });
  }
  
  return results;
}

module.exports = {
  generatePlaceholderPDF,
  generateSubmissionPDFs
};
